Watching for file changes with StatReloader
Not Found: /accounts/login/media/plnt.png
Form errors: 
Not Found: /accounts/register/media/plnt.png
Not Found: /accounts/register/media/plnt.png
Not Found: /accounts/login/media/plnt.png
Not Found: /accounts/login/media/plnt.png
Watching for file changes with StatReloader
Form errors: 
Not Found: /accounts/register/media/plnt.png
Watching for file changes with StatReloader
Not Found: /accounts/register/media/plnt.png
Not Found: /accounts/register/media/plnt.png
Not Found: /accounts/register/media/plnt.png
Form errors: <ul class="errorlist"><li>username<ul class="errorlist"><li>Обязательное поле.</li></ul></li></ul>
Not Found: /accounts/register/media/plnt.png
C:\Users\user\PycharmProjects\b\bishkek_green\core\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\PycharmProjects\b\bishkek_green\core\forms.py changed, reloading.
Watching for file changes with StatReloader
Form errors: <ul class="errorlist"><li>username<ul class="errorlist"><li>Обязательное поле.</li></ul></li></ul>
Not Found: /accounts/register/media/plnt.png
Form errors: <ul class="errorlist"><li>username<ul class="errorlist"><li>Обязательное поле.</li></ul></li></ul>
Not Found: /accounts/register/media/plnt.png
Form errors: <ul class="errorlist"><li>email<ul class="errorlist"><li>Введите правильный адрес электронной почты.</li></ul></li><li>password2<ul class="errorlist"><li>Введённый пароль слишком похож на имя пользователя.</li></ul></li></ul>
Not Found: /accounts/register/media/plnt.png
User diddy registered successfully.
Not Found: /request/media/plnt.png
Not Found: /request/media/plnt.png
Not Found: /map/media/plnt.png
Not Found: /request/media/plnt.png
Internal Server Error: /contact/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\b\bishkek_green\core\views.py", line 110, in contact
    return render(request, 'contact.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: contact.html
Method Not Allowed (GET): /accounts/logout/
Method Not Allowed: /accounts/logout/
Method Not Allowed (GET): /accounts/logout/
Method Not Allowed: /accounts/logout/
